config/routes.rb
Rails.application.routes.draw do
  resources :posts
    get "posts/index"
    root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true,
                    length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end
    
    def new
        @post = Post.new
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def create
        @post = Post.new(post_params)
 
        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end

     
    def update
        @post = Post.find(params[:id])
    
        if @post.update(post_params)
        redirect_to @post
        else
        render 'edit'
        end
    end


    def destroy
        @post = Post.find(params[:id])
        @post.destroy
    
        redirect_to posts_path
    end

    private
    def post_params
        params.require( :title ).permit( :title, :content)
        #params.permit( :title, :content)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
 
<%= form_for(@post) do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li style="color:red;"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>My Blog</h1>
 
<%= link_to 'New post', new_post_path %>
<table>
    <tr>
        <th>Title</th>
        <th>Content</th>
    </tr>
 
  <% @posts.each do |post| %>
    <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post_path(post) %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post_path(post),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li style='color:red;'><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    </p>

    <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
    </p>

    <p>
    <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>